language: php
php:
 - 5.3
 - 5.4
 - 5.5
branches:
 only:
  - master
before_script:
 - composer self-update
 - composer install --dev
 - composer update
script:
 - cd tests
 - pwd
 - php ../vendor/phpunit/phpunit/phpunit tests/

